search feature
aniyahb/AniyahBunn_Capstone pull request #18
Opened 2024-07-16 06:55 UTC by aniyahb

The feature to search for recipes based on keywords, ingredients, etc.. is complete.

2024-07-16 15:23 UTC, KatsiarynaMashokha commented on frontend/src/App.jsx
> +  console.log(searchQuery)
remove console.log. You should not be committing non production code

2024-07-16 15:25 UTC, KatsiarynaMashokha commented on frontend/src/HomePage/HomePage.jsx
> +function HomePage(props) {
you can destructure props right in here so below you can use `setSearch`

2024-07-16 15:26 UTC, KatsiarynaMashokha commented on frontend/src/MainHeader/MainHeader.css
> +    padding-top: 20px;
nit: remove empty spaces

2024-07-16 15:26 UTC, KatsiarynaMashokha commented on frontend/src/MainHeader/MainHeader.jsx
> +function MainHeader(props) {
same with destructure in here

2024-07-16 15:27 UTC, KatsiarynaMashokha commented on frontend/src/RecipeList/RecipeList.jsx
> +        setModalOpen(!modalOpen);
can you just put here `false`? Since close function should only be closing the modal?

2024-07-16 15:29 UTC, KatsiarynaMashokha commented on frontend/src/SearchBar/SearchBar.jsx
> +        navigate('/searched/'+input);
you can use template literals in here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
so it'll be `/searched/${input}`, you would need to wrap in with quotes like ``

2024-07-16 15:29 UTC, KatsiarynaMashokha commented on frontend/src/SearchBar/SearchBar.jsx
> +    }
remove this

2024-07-16 15:30 UTC, KatsiarynaMashokha commented on frontend/src/SearchBar/SearchBar.jsx
> +        {/* <button id="search" className="search-results" type="button" >
same unused code

2024-07-16 15:30 UTC, KatsiarynaMashokha commented on frontend/src/SearchedModal/SearchedModal.jsx
> +                {/* <ul>
remove this

2024-07-16 23:06 UTC, KatsiarynaMashokha approved these changes

2024-07-17 15:25 UTC, alishahimtiaz requested changes

2024-07-17 15:25 UTC, alishahimtiaz commented on frontend/src/SearchedPage/SearchedPage.jsx
> +        // setPickedInstructions(instructions)
Commented out code

2024-07-17 15:25 UTC, alishahimtiaz commented on frontend/src/SearchedPage/SearchedPage.jsx
> +        // setModalOpen(!modalOpen)
Here to

2024-07-17 15:25 UTC, alishahimtiaz commented on frontend/src/SearchedPage/SearchedPage.jsx
> +            console.log(data)
Remove console.log

2024-07-17 15:25 UTC, alishahimtiaz commented on frontend/src/SearchedModal/SearchedModal.jsx
> +    console.log(ingredients)
Remove console log

2024-07-17 15:25 UTC, alishahimtiaz commented on frontend/src/SearchedPage/SearchedPage.jsx
> +                console.log(input)
Remove all console logs

2024-07-17 18:11 UTC, merged